"""Initial schema: users, interventions, documents, signatures, settings

Revision ID: 4b31cf18c612
Revises: 
Create Date: 2026-04-25 09:04:11.724783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b31cf18c612'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('STRING', 'INTEGER', 'BOOLEAN', 'JSON', 'ENCRYPTED', name='settingtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'COLLABORATOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('interventions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('client_nom', sa.String(length=255), nullable=False),
    sa.Column('client_prenom', sa.String(length=255), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('client_telephone', sa.String(length=50), nullable=False),
    sa.Column('client_adresse', sa.Text(), nullable=True),
    sa.Column('client_code_postal', sa.String(length=10), nullable=True),
    sa.Column('client_ville', sa.String(length=255), nullable=True),
    sa.Column('date_rdv', sa.DateTime(), nullable=False),
    sa.Column('heure_rdv', sa.String(length=20), nullable=True),
    sa.Column('duree_estimee', sa.Integer(), nullable=True),
    sa.Column('description_travaux', sa.Text(), nullable=True),
    sa.Column('montant_devis_ht', sa.Integer(), nullable=True),
    sa.Column('montant_devis_ttc', sa.Integer(), nullable=True),
    sa.Column('logement_plus_2_ans', sa.String(length=1), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'SIGNED', 'PARTIAL', 'EXPIRED', 'CANCELLED', name='interventionstatus'), nullable=False),
    sa.Column('signature_token', sa.String(length=255), nullable=True),
    sa.Column('signature_link_expires_at', sa.DateTime(), nullable=True),
    sa.Column('sms_sent_count', sa.Integer(), nullable=False),
    sa.Column('last_sms_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_date_rdv'), 'interventions', ['date_rdv'], unique=False)
    op.create_index(op.f('ix_interventions_google_event_id'), 'interventions', ['google_event_id'], unique=True)
    op.create_index(op.f('ix_interventions_signature_token'), 'interventions', ['signature_token'], unique=True)
    op.create_index(op.f('ix_interventions_status'), 'interventions', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intervention_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PROCES_VERBAL', 'ATTESTATION_TVA', 'DELEGATION_PAIEMENT', 'FICHE_TRAVAUX', name='documenttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'SIGNED', 'REJECTED', 'EXPIRED', name='documentstatus'), nullable=False),
    sa.Column('file_path_unsigned', sa.Text(), nullable=True),
    sa.Column('file_path_signed', sa.Text(), nullable=True),
    sa.Column('yousign_request_id', sa.String(length=255), nullable=True),
    sa.Column('yousign_document_id', sa.String(length=255), nullable=True),
    sa.Column('yousign_signature_link', sa.Text(), nullable=True),
    sa.Column('signature_provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_intervention_id'), 'documents', ['intervention_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_yousign_request_id'), 'documents', ['yousign_request_id'], unique=False)
    op.create_table('signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intervention_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SIGNED', 'REJECTED', name='signaturestatus'), nullable=False),
    sa.Column('signature_image', sa.Text(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('signer_ip', sa.String(length=45), nullable=True),
    sa.Column('signer_user_agent', sa.Text(), nullable=True),
    sa.Column('signer_name_typed', sa.String(length=255), nullable=True),
    sa.Column('signer_consent_text', sa.Text(), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('yousign_signature_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signatures_document_id'), 'signatures', ['document_id'], unique=False)
    op.create_index(op.f('ix_signatures_intervention_id'), 'signatures', ['intervention_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signatures_intervention_id'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_document_id'), table_name='signatures')
    op.drop_table('signatures')
    op.drop_index(op.f('ix_documents_yousign_request_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_intervention_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_interventions_status'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_signature_token'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_google_event_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_date_rdv'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
