"""add_sms_logs_table

Revision ID: 6b177b36d261
Revises: 4b31cf18c612
Create Date: 2026-04-26 11:41:38.286457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b177b36d261'
down_revision: Union[str, None] = '4b31cf18c612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intervention_id', sa.UUID(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sms_type', sa.Enum('SIGNATURE_INITIAL', 'SIGNATURE_RELANCE', 'RDV_RAPPEL', 'AUTRE', name='smstype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'UNDELIVERED', name='smsstatus'), nullable=False),
    sa.Column('twilio_sid', sa.String(length=64), nullable=True),
    sa.Column('twilio_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_logs_intervention_id'), 'sms_logs', ['intervention_id'], unique=False)
    op.create_index(op.f('ix_sms_logs_phone'), 'sms_logs', ['phone'], unique=False)
    op.create_index(op.f('ix_sms_logs_sent_at'), 'sms_logs', ['sent_at'], unique=False)
    op.create_index(op.f('ix_sms_logs_sms_type'), 'sms_logs', ['sms_type'], unique=False)
    op.create_index(op.f('ix_sms_logs_status'), 'sms_logs', ['status'], unique=False)
    op.create_index(op.f('ix_sms_logs_twilio_sid'), 'sms_logs', ['twilio_sid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_logs_twilio_sid'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_status'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_sms_type'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_sent_at'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_phone'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_intervention_id'), table_name='sms_logs')
    op.drop_table('sms_logs')
    # ### end Alembic commands ###
